name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: Widnows. Currently insta fails due to path sep
        os: [ubuntu-latest] #, windows-latest, macOS-latest]
        rust: [stable]
        # include:
        #   - rust: beta
        #     os: ubuntu-latest
        #   - rust: nightly
        #     os: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # THIS DOESN"T WORK LOL
    # - name: Cache Deps
    #   uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/.cargo/registry
    #       ~/.cargo/git
    #       target
    #     key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: cargo test
      #    - name: Cypress run
      #      uses: cypress-io/github-action@v2
      #      with:
      #        start: make serve-dummy
